version: "3"

services:
  webapp:
    build: .
    ports: [ "8081:80" ]
    volumes:
      - ./:/app/
    command: uvicorn main:app --host 0.0.0.0 --port $PORT --reload
    env_file: [ .env ]

  db:
    image: postgres:14
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    links: [ webapp ]

#  locust:
#    image: locustio/locust
#    ports: [ "8089:8089" ]
#    volumes:
#      - ./:/mnt/locust
#    command: -f /mnt/locust/locustfile.py --master -H http://webapp:80
#
#  locust_worker:
#    image: locustio/locust
#    volumes:
#      - ./:/mnt/locust
#    command: -f /mnt/locust/locustfile.py --worker --master-host locust
#    links: [ locust ]

volumes:
  pgdata:
