version: "3"

services:
  webapp:
    build: .
    ports: [ "8081:80" ]
    volumes:
      - ./:/app/
    command: gunicorn --reload --bind 0.0.0.0:80 main:app
    env_file: [ .env ]

  db:
    image: postgres:13
    ports: [ "5432:5432" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    links: [ webapp ]

volumes:
  pgdata:
