[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fantasy-recipe"
version = "1.0.0"
description = "Fantasy recipes"
authors = []

[tool.poetry.dependencies]
alembic = "^1.7.4"
appdirs = "^1.4.4"
Flask = "^2.0.2"
gunicorn = "^20.1.0"
psycopg2-binary = "^2.9.1"
pydantic = "^1.8.2"
python = "^3.9"
SQLAlchemy = "^1.4.25"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pytest = "^6.2.5"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
