[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fantasy-recipe"
version = "1.0.0"
description = "Fantasy recipes"
authors = []

[tool.poetry.dependencies]
alembic = "^1.5.6"
appdirs = "^1.4.4"
Flask = "^1.1.2"
gunicorn = "^20.0.4"
psycopg2-binary = "^2.8.6"
pydantic = "^1.8.1"
python = "^3.9"
python-dotenv = "^0.14.0"
SQLAlchemy = "^1.3.23"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
mypy = "^0.812"
pytest = "^6.2.2"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
