[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fantasy-recipe"
version = "1.0.0"
description = "Fantasy recipes"
authors = []

[tool.poetry.dependencies]
alembic = "^1.7.4"
appdirs = "^1.4.4"
asyncpg = "^0.24.0"
fastapi = "^0.70.0"
Jinja2 = "^3.0.2"
pydantic = "^1.8.2"
python = "^3.9"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.25"}
uvicorn = {extras = ["standard"], version = "^0.15.0"}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-asyncio = "^0.15.1"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
