[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fantasy-recipe"
version = "2.0.0"
description = "Fantasy recipes"
authors = []

[tool.poetry.dependencies]
alembic = "^1.7.4"
appdirs = "^1.4.4"
asyncpg = "^0.24.0"
fastapi = "^0.70.0"
Jinja2 = "^3.0.2"
passlib = {extras = ["argon2"], version = "^1.7.4"}
pydantic = "^1.8.2"
python = "^3.9"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
python-multipart = "^0.0.5"
SQLAlchemy = {extras = ["asyncio"], version = "^1.4.25"}
uvicorn = {extras = ["standard"], version = "^0.15.0"}

[tool.poetry.dev-dependencies]
black = "^21.9b0"
mypy = "^0.910"
pytest = "^6.2.5"
pytest-asyncio = "^0.16.0"
coverage = {extras = ["toml"], version = "^6.0.2"}

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'

[tool.mypy]
ignore_missing_imports = true
warn_no_return = false
warn_return_any = false

[tool.coverage.run]
branch = true
omit = ["tests/*"]
[tool.coverage.report]
skip_empty = true
show_missing = true
