[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "fantasy-recipe"
version = "1.0.0"
description = "Fantasy recipes"
authors = []

[tool.poetry.dependencies]
alembic = "^1.6.2"
appdirs = "^1.4.4"
Flask = "^2.0.0"
gunicorn = "^20.1.0"
psycopg2-binary = "^2.8.6"
pydantic = "^1.8.2"
python = "^3.9"
python-dotenv = "^0.14.0"
SQLAlchemy = "1.4.15"

[tool.poetry.dev-dependencies]
black = "^21.5b1"
mypy = "^0.812"
pytest = "^6.2.4"

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
