name: Python application

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t local .
    - name: Install dev tools
      run: |
        docker run --name app local pdm install
        docker commit app app
    - name: Check code style
      run: docker run app python -m black --check .
    - name: Check static types
      run: docker run app python -m mypy .
    - name: Test with pytest
      run: docker run app sh -c 'pdm run test'
