name: Python application

on: push

env:
  DATABASE_URL: postgresql://postgres:password@db:5432/postgres

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -t local .
    - name: Install dev tools
      run: |
        docker run --name app local pip install .[dev]
        docker commit app app
    - name: Check code style
      run: docker run app black --check .
    # - name: Check static types
    #   run: docker run app mypy .
    - name: Test with pytest
      run: docker run -e DATABASE_URL app coverage run -m pytest tests/ --junitxml=junit.xml -m "not webtest"
